---
roles:
  - name: docker
    src: git@gitlab.com:ansible-roles543108/docker-role.git
    scm: git
    version: main

  - name: nginx
    src: git@gitlab.com:ansible-roles543108/docker-role.git
    scm: git
    version: main
