---
- name: Обновить кэш пакетов
  apt:
    update_cache: yes
  become: yes
  changed_when: false

- name: Установить необходимые пакеты OpenVPN
  apt:
    name: "{{ openvpn_packages }}"
    state: present
  become: yes

- name: Проверить существование каталога Easy-RSA
  block:
    - name: Проверить, существует ли каталог Easy-RSA
      stat:
        path: "{{ easy_rsa_path }}"
      register: easy_rsa_exists

    - name: Создать каталог Easy-RSA, если он отсутствует
      command: make-cadir "{{ easy_rsa_path }}"
      become: yes
      when: not easy_rsa_exists.stat.exists

- name: Проверить существование каталога PKI
  block:
    - name: Проверить, существует ли каталог PKI
      stat:
        path: "{{ easy_rsa_pki_path }}"
      register: pki_exists

    - name: Инициализировать каталог PKI, если он отсутствует
      command: ./easyrsa init-pki
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not pki_exists.stat.exists

- name: Создать и управлять сертификатами CA и сервера
  block:
    - name: Проверить, существует ли сертификат CA
      stat:
        path: "{{ easy_rsa_pki_path }}/ca.crt"
      register: ca_cert

    - name: Создать сертификат CA без пароля
      shell: echo "openvpn_ca" | ./easyrsa build-ca nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not ca_cert.stat.exists

    - name: Проверить, существует ли серверный ключ
      stat:
        path: "{{ easy_rsa_pki_path }}/private/server.key"
      register: server_key

    - name: Сгенерировать запрос на серверный сертификат без пароля
      shell: echo "openvpn_server" | ./easyrsa gen-req server nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not server_key.stat.exists

    - name: Проверить, существует ли серверный сертификат
      stat:
        path: "{{ easy_rsa_pki_path }}/issued/server.crt"
      register: server_cert

    - name: Подписать серверный сертификат
      shell: echo "yes" | ./easyrsa sign-req server server
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not server_cert.stat.exists

    - name: Проверить, существуют ли параметры Диффи-Хеллмана
      stat:
        path: "{{ easy_rsa_pki_path }}/dh.pem"
      register: dh_params

    - name: Сгенерировать параметры Диффи-Хеллмана
      command: ./easyrsa gen-dh
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not dh_params.stat.exists

    - name: Проверить, существует ли TLS-ключ
      stat:
        path: "{{ easy_rsa_pki_path }}/ta.key"
      register: tls_key

    - name: Сгенерировать TLS-ключ
      command: openvpn --genkey --secret pki/ta.key
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not tls_key.stat.exists

- name: Подготовить каталог конфигурации OpenVPN
  file:
    path: /etc/openvpn
    state: directory
    mode: '0755'
  become: yes

- name: Скопировать сертификаты и ключи в каталог OpenVPN
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    force: no
  with_items:
    - { src: "{{ easy_rsa_pki_path }}/ca.crt", dest: "{{ openvpn_config_path }}/ca.crt" }
    - { src: "{{ easy_rsa_pki_path }}/issued/server.crt", dest: "{{ openvpn_config_path }}/server.crt" }
    - { src: "{{ easy_rsa_pki_path }}/private/server.key", dest: "{{ openvpn_config_path }}/server.key" }
    - { src: "{{ easy_rsa_pki_path }}/dh.pem", dest: "{{ openvpn_config_path }}/dh.pem" }
    - { src: "{{ easy_rsa_pki_path }}/ta.key", dest: "{{ openvpn_config_path }}/ta.key" }
  become: yes

- name: Применить конфигурацию OpenVPN-сервера
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  become: yes

- name: Проверить, работает ли OpenVPN с ожидаемой конфигурацией
  shell: pgrep -f "openvpn.*--config /etc/openvpn/server.conf.*"
  register: openvpn_process
  ignore_errors: true
  changed_when: false

- name: Запустить OpenVPN, если он не работает
  command: openvpn --config /etc/openvpn/server.conf
  async: 30
  poll: 0
  become: yes
  when: openvpn_process.rc != 0

- name: Сгенерировать конфигурационный файл клиента
  template:
    src: client.ovpn.j2
    dest: "client.ovpn"
