---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True

driver:
  name: docker

platforms:
  - name: master-node
    image: geerlingguy/docker-ubuntu2004-ansible
    groups:
      - master
    privileged: true
    pre_build_image: true
    networks:
      - name: postgresql-network

  - name: replica-node
    image: geerlingguy/docker-ubuntu2004-ansible
    groups:
      - replica
    privileged: true
    pre_build_image: true
    networks:
      - name: postgresql-network

provisioner:
  name: ansible

verifier:
  name: ansible
